[project]
name = "auto-pricing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "pydantic-settings>=2.15.0",
    "uvicorn[standard]>=0.52.1",
]

[project.scripts]
auto-pricing = "auto_pricing:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
